on: push
name: deploy
jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: _json_key
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        repository: ${{ github.repository }}
        tag: latest